package unityEngine;
@:native("UnityEngine.Camera") extern class Camera extends Behaviour {
	var fieldOfView:Float;
	var nearClipPlane:Float;
	var farClipPlane:Float;
	var renderingPath:unityEngine.RenderingPath;
	var actualRenderingPath:unityEngine.RenderingPath;
	var hdr:Bool;
	var orthographicSize:Float;
	var orthographic:Bool;
	var transparencySortMode:unityEngine.TransparencySortMode;
	var depth:Float;
	var aspect:Float;
	var cullingMask:Int;
	var backgroundColor:unityEngine.Color;
	var rect:unityEngine.Rect;
	var pixelRect:unityEngine.Rect;
	var targetTexture:unityEngine.RenderTexture;
	var worldToCameraMatrix:unityEngine.Matrix4x4;
	var projectionMatrix:unityEngine.Matrix4x4;
	var velocity:unityEngine.Vector3;
	var clearFlags:unityEngine.CameraClearFlags;
	var useOcclusionCulling:Bool;
	var layerCullDistances:unityEngine.Array<Float>;
	var layerCullSpherical:Bool;
	var depthTextureMode:unityEngine.DepthTextureMode;
	function ResetWorldToCameraMatrix():Void;
	function ResetProjectionMatrix():Void;
	function ResetAspect():Void;
	function WorldToScreenPoint(position:unityEngine.Vector3):unityEngine.Vector3;
	function WorldToViewportPoint(position:unityEngine.Vector3):unityEngine.Vector3;
	function ViewportToWorldPoint(position:unityEngine.Vector3):unityEngine.Vector3;
	function ScreenToWorldPoint(position:unityEngine.Vector3):unityEngine.Vector3;
	function ScreenToViewportPoint(position:unityEngine.Vector3):unityEngine.Vector3;
	function ViewportToScreenPoint(position:unityEngine.Vector3):unityEngine.Vector3;
	function ViewportPointToRay(position:unityEngine.Vector3):unityEngine.Ray;
	function ScreenPointToRay(position:unityEngine.Vector3):unityEngine.Ray;
	function Render():Void;
	function RenderWithShader(shader:unityEngine.Shader, replacementTag:String):Void;
	function SetReplacementShader(shader:unityEngine.Shader, replacementTag:String):Void;
	function ResetReplacementShader():Void;
	function RenderToCubemap(cubemap:unityEngine.RenderTexture, faceMask:Int = 63):Bool;
	function CopyFrom(other:unityEngine.Camera):Void;
	static var main:unityEngine.Camera;
	static var current:unityEngine.Camera;
	static var allCameras:unityEngine.Array<Camera>;
}