package unityEngine;
@:native("UnityEngine.GUI") extern class GUI {
	static var skin:unityEngine.GUISkin;
	static var color:unityEngine.Color;
	static var backgroundColor:unityEngine.Color;
	static var contentColor:unityEngine.Color;
	static var changed:Bool;
	static var enabled:Bool;
	static var matrix:unityEngine.Matrix4x4;
	static var tooltip:String;
	static var depth:Int;
	function Label(position:unityEngine.Rect, content:unityEngine.GUIContent, style:unityEngine.GUIStyle):Void;
	function DrawTexture(position:unityEngine.Rect, image:unityEngine.Texture, scaleMode:unityEngine.ScaleMode = ScaleMode.StretchToFill, alphaBlend:unityEngine.boolean = true, imageAspect:unityEngine.float = 0):Void;
	function DrawTextureWithTexCoords(position:unityEngine.Rect, image:unityEngine.Texture, texCoords:unityEngine.Rect, alphaBlend:unityEngine.boolean = true):Void;
	function Box(position:unityEngine.Rect, content:unityEngine.GUIContent, style:unityEngine.GUIStyle):Void;
	function Button(position:unityEngine.Rect, content:unityEngine.GUIContent, style:unityEngine.GUIStyle):Bool;
	function RepeatButton(position:unityEngine.Rect, content:unityEngine.GUIContent, style:unityEngine.GUIStyle):Bool;
	function TextField(position:unityEngine.Rect, text:String, maxLength:Int, style:unityEngine.GUIStyle):String;
	function PasswordField(position:unityEngine.Rect, password:String, maskChar:unityEngine.char, maxLength:Int, style:unityEngine.GUIStyle):String;
	function TextArea(position:unityEngine.Rect, text:String, maxLength:Int, style:unityEngine.GUIStyle):String;
	function SetNextControlName(name:String):Void;
	function GetNameOfFocusedControl():String;
	function FocusControl(name:String):Void;
	function Toggle(position:unityEngine.Rect, value:Bool, content:unityEngine.GUIContent, style:unityEngine.GUIStyle):Bool;
	function Toolbar(position:unityEngine.Rect, selected:Int, contents:unityEngine.Array<GUIContent>, style:unityEngine.GUIStyle):Int;
	function SelectionGrid(position:unityEngine.Rect, selected:Int, contents:unityEngine.Array<GUIContent>, xCount:Int, style:unityEngine.GUIStyle):Int;
	function HorizontalSlider(position:unityEngine.Rect, value:Float, leftValue:Float, rightValue:Float, slider:unityEngine.GUIStyle, thumb:unityEngine.GUIStyle):Float;
	function VerticalSlider(position:unityEngine.Rect, value:Float, topValue:Float, bottomValue:Float, slider:unityEngine.GUIStyle, thumb:unityEngine.GUIStyle):Float;
	function HorizontalScrollbar(position:unityEngine.Rect, value:Float, size:Float, leftValue:Float, rightValue:Float, style:unityEngine.GUIStyle):Float;
	function VerticalScrollbar(position:unityEngine.Rect, value:Float, size:Float, topValue:Float, bottomValue:Float, style:unityEngine.GUIStyle):Float;
	function BeginGroup(position:unityEngine.Rect, content:unityEngine.GUIContent, style:unityEngine.GUIStyle):Void;
	function EndGroup():Void;
	function BeginScrollView(position:unityEngine.Rect, scrollPosition:unityEngine.Vector2, viewRect:unityEngine.Rect, alwaysShowHorizontal:Bool, alwaysShowVertical:Bool, horizontalScrollbar:unityEngine.GUIStyle, verticalScrollbar:unityEngine.GUIStyle):unityEngine.Vector2;
	function EndScrollView(handleScrollWheel:Bool):Void;
	function ScrollTo(position:unityEngine.Rect):Void;
	function Window(id:Int, clientRect:unityEngine.Rect, func:unityEngine.WindowFunction, title:unityEngine.GUIContent, style:unityEngine.GUIStyle):unityEngine.Rect;
	function DragWindow():Void;
	function BringWindowToFront(windowID:Int):Void;
	function BringWindowToBack(windowID:Int):Void;
	function FocusWindow(windowID:Int):Void;
	function UnfocusWindow():Void;
}