package unityEngine;
@:native("UnityEngine.GUIStyle") extern class GUIStyle {
	var name:String;
	var normal:unityEngine.GUIStyleState;
	var hover:unityEngine.GUIStyleState;
	var active:unityEngine.GUIStyleState;
	var onNormal:unityEngine.GUIStyleState;
	var onHover:unityEngine.GUIStyleState;
	var onActive:unityEngine.GUIStyleState;
	var focused:unityEngine.GUIStyleState;
	var onFocused:unityEngine.GUIStyleState;
	var border:unityEngine.RectOffset;
	var margin:unityEngine.RectOffset;
	var padding:unityEngine.RectOffset;
	var overflow:unityEngine.RectOffset;
	var font:unityEngine.Font;
	var imagePosition:unityEngine.ImagePosition;
	var alignment:unityEngine.TextAnchor;
	var wordWrap:Bool;
	var clipping:unityEngine.TextClipping;
	var contentOffset:unityEngine.Vector2;
	var fixedWidth:Float;
	var fontSize:Int;
	var fontStyle:unityEngine.FontStyle;
	var fixedHeight:Float;
	var stretchWidth:Bool;
	var stretchHeight:Bool;
	var lineHeight:Float;
	function new(other:unityEngine.GUIStyle):Void;
	//function Draw(position:unityEngine.Rect, content:unityEngine.GUIContent, controlID:Int, on:unityEngine.boolean = false):Void;
	function DrawCursor(position:unityEngine.Rect, content:unityEngine.GUIContent, controlID:Int, Character:Int):Void;
	function DrawWithTextSelection(position:unityEngine.Rect, content:unityEngine.GUIContent, controlID:Int, firstSelectedCharacter:Int, lastSelectedCharacter:Int):Void;
	function GetCursorPixelPosition(position:unityEngine.Rect, content:unityEngine.GUIContent, cursorStringIndex:Int):unityEngine.Vector2;
	function GetCursorStringIndex(position:unityEngine.Rect, content:unityEngine.GUIContent, cursorPixelPosition:unityEngine.Vector2):Int;
	function CalcSize(content:unityEngine.GUIContent):unityEngine.Vector2;
	function CalcScreenSize(contentSize:unityEngine.Vector2):unityEngine.Vector2;
	function CalcHeight(content:unityEngine.GUIContent, width:Float):Float;
	//function CalcMinMaxWidth(content:unityEngine.GUIContent, out minWidth:Float, out maxWidth:Float):Void;
}